apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ident_label}}
spec:
  replicas: {{replicas}}
  template:
    metadata:
      name: {{ident_label}}
      labels:
        app: {{ident_label}}
      annotations:
        {{#spec_annotations}}
        {{key}}: "{{val}}"
        {{/spec_annotations}}
    spec:
      volumes:
      - name: localconfig
        secret:
          secretName: avengers-local-conf
      containers:
      - name: avengers-web-proxy
        image: {{registry}}/{{image_proxy}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{port_proxy}}
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: "0.1"
            memory: 50Mi
      - name: avengers-web
        image: {{registry}}/{{image_web}}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: localconfig
          mountPath: "/srv/http/web/conf/app.local.conf"
          subPath: "app.local.conf"
        ports:
        - containerPort: {{port_web}}
        env:
        {{#env}}
        - name: {{key}}
          value: "{{val}}"
        {{/env}}
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /system/loadbalancer
            port: {{port_proxy}}
