language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
install:
  - 'pip install -U pip'
  - 'pip install -U pipenv'
  - 'pipenv lock'
  - 'pipenv install --dev'
script: 'python -m pytest tests'
after_success:
  - pipenv run py.test --cov=vindaloo --cov-report term tests
  - codecov
