apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ident_label}}
spec:
  schedule: "{{schedule}}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: avengers-robot
        spec:
          restartPolicy: Never
          volumes:
          - name: localconfig
            secret:
              secretName: avengers-local-conf
          - name: robotpasswords
            secret:
              secretName: avengers-robot-pass-conf
          - name: robotconf
            configMap:
              name: avengers-robot-conf
              items:
              - key: robot.env.conf
                path: robot.conf.dev
          containers:
          - name: {{ident_label}}
            image: {{registry}}/{{image}}
            command: ["sh", "-c", "{{{command}}}"]
            env:
            {{#env}}
            - name: {{key}}
              value: {{val}}
            {{/env}}
            volumeMounts:
            - name: localconfig
              mountPath: "/home/avengers/conf/app.local.conf"
              subPath: "app.local.conf"
            - name: robotpasswords
              mountPath: "/home/avengers/robot/conf/robot.passwd.conf"
              subPath: "robot.passwd.conf"
            - name: robotconf
              mountPath: "/home/avengers/robot/conf/robot.conf.dev"
              subPath: robot.conf.dev
            resources:
              requests:
                cpu: "0.5"
                memory: 500Mi
              limits:
                cpu: 4
                memory: 8000Mi
