apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: cluster-name
spec:
  selector:
    matchLabels:
      app: avengers-robot
  env:
    - name: KUBERNETES_CLUSTER
      value: "ko1"
